language: csharp
dotnet: 2.2.401

solution: ./src/Isop.sln
install:
  - msbuild /t:restore src

script: 
  - msbuild src
  - dotnet test -f netcoreapp2.1 src/Tests/Tests.csproj
branches:
  only: 
    - master
    - isop