language: csharp
dotnet: 2.2.401

solution: ./Isop.sln
install:
  - msbuild /t:restore . 

script: 
  - msbuild . 
  - dotnet test -f netcoreapp2.1 tests/Tests/Tests.csproj
branches:
  only: 
    - master
    - isop