language: objective-c

env:
  matrix:
    - MONO_VERSION="3.8.0"
  global:
    - EnableNuGetPackageRestore=false

install:
  - wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script: 
  - bundle install 
  - rake install_packages
  - rake build
  - /Library/Frameworks/Mono.framework/Versions/${MONO_VERSION}/bin/nunit-console4 ./src/Tests/bin/Debug/Tests.dll
