version: 1.0.{build}
configuration: Release
before_build:
  - bundle install
  - rake restore
build:
  project: src\Isop.sln
  verbosity: minimal
  publish_nuget: true
nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true
